### ISSUE TITLE
1920x1080 script not redeeming

### ISSUE THREAD

**Issue by jaaneh** [zonedguy/zoned#1]
Hey, thanks for the scripts!

The 1920x1080 scripts all end up missing the bountes when going to redeem. My res is set correctly.

![](https://jaany.xyz/i/3milq.png)

**Comment by zonedguy** [comment]
Odd, I've had hundreds of successful runs for those resolution files between my clan and me. That image shows it is considerably short on the X axis. Please verify that you are not running at 1920 x 1440 instead?

**Comment by jaaneh** [comment]
Strange. Both my monitor and d2 are running 1920x1080. Everything works fine up until the claiming and after.

**Comment by zonedguy** [comment]
Strange indeed. You can update the scripts to work for you be editing the files in notepad.

MouseMove is the command that changes the cursor and it does so with X, Y values. In this instance look for the text that says:

; Redeem 7 Paradox bounties

MouseMove, 190, 0, 5, R

190 is the X value which you need to change. I'm guessing you want something around 260 or more, but you'll have to test it through trial and error. Make sure once you find the right value that also put that value in the code below as a negative so the cursor moves back to the original spot:

; Exit Quest menu and return to neutral position

Send {Esc down}
Sleep, 150
Send {Esc up}
Sleep, 1000
MouseMove, -190, 0, 5, R
Sleep, 1200

**Comment by jaaneh** [comment]
Cheers. 295/-295 seems to work fine for me.

Also had to change these to hit the dismantle correctly
; Open inventory, go to primary weapons then first weapon slot
`MouseMove, -650, 120, 5, R` to `MouseMove, -590, 120, 5, R`

; Exit Bounties and go back to neutral position
`MouseMove, 650, -120, 5, R` to `MouseMove, 590, -120, 5, R`

Works like a charm now 😄

**Comment by zonedguy** [comment]
Identified the issue. Running in fullscreen windowed mode on a screen with a higher resolution causes runs AHK at the native resolution not at the game resolution. This causes the relative movements to miss targets. Run the script while in fullscreen or normal windowed modes

**Comment by jaaneh** [comment]
Strange. These are the settings I'm running. With 1920x1080 monitor (VG248QE) Still requires me to run my custom script though.

![](https://jaany.xyz/i/n4pys.png)

**Comment by zonedguy** [comment]
What FOV are you using? Are you rendering above 100%?

**Comment by jaaneh** [comment]
FOV 105, rendering 100%

**Comment by jaaneh** [comment]
I figured out my issue. I play with screen bounds as tiny as possible (found it boosts a couple fps for me). Running main script with default screen bounds work fine.
