### ISSUE TITLE
not claiming bounties

### ISSUE THREAD

**Issue by joeboo87** [zonedguy/zoned#4]
ive set to 1080 fullscreen maxed bounds and it wont claim my bounties any insight into how i can fix this would be appreciated. dont know if you can reply here

**Comment by zonedguy** [comment]
Try windowed version, other than that no idea. Removed your email address from your comment as this is publicly available and you'd be inviting spam.

**Comment by joeboo87** [comment]
So I read another one of the other comments issue#1 I believe and adjusted it to 295 and -295 like he did and works great. You are amazing dude thank you so much for the leg work and creating this. Also thank you for takin my email down

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 25, 2020 at 5:19 PM, zonedguy<notifications@github.com> wrote:   
Try windowed version, other than that no idea. Removed your email address from your comment as this is publicly available and you'd be inviting spam.
