### ISSUE TITLE
AutoHotKey crashes after redeeming perfect paradox bounties

### ISSUE THREAD

**Issue by gilbertw1** [zonedguy/zoned#5]
Hi,

Using the latest version of the script as of b3c8186, it seems to stop functioning and crash AutoHotKey directly after redeeming each of the perfect paradox bounties, but before dismantling any of the guns. I'm running this using 1080p full screen and using F4 to run the full 12 cycles.

I did use an older version of the script (chosen relatively arbitrarily) from e3577e0 that works properly as far as I can tell.

Thanks for the hard work, this script is a life saver!

**Comment by zonedguy** [comment]
Updated with an Esc key bind kill script. That caused the Esc bindings in the existing scripts to also kill AHK. The Esc kill script has been rebound as LCtrl + Esc so resolve the issue. Thanks for the report.
